name: fridge_mate
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  date_format: ^2.0.7
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.3
  firebase_storage: ^12.1.2
  cloud_firestore: ^5.2.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/FridgeMate_Logo.png